### ISSUE TITLE
Usage in non-JS form submit

### ISSUE THREAD

**Issue by 13s5lp** [Psifi-Solutions/csrf-sync#4]
Is there some way this can be used when submitting a `<form method="POST">` without javascript? In https://github.com/expressjs/csurf, I believe this can be done with a field in the request body, it checks `req.body._csrf` as well as `req.headers["csrf-token"]`.

**Comment by psibean** [comment]
This has been fixed and resolved.

Version 3.0.0 has been released and now supports a `getTokenFromRequest` prop so you can handle getting the token out of the request in any manner you see fit.
